### PR TITLE
Fix windows installation

### LINKED ISSUE #107: JDK installed in wrong directory on Windows
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

In https://github.com/conda-forge/openjdk-feedstock/commit/5f998d401e4d97c50dc24aa2177945e655a4833c the `JAVA_HOME` changed to `<env_root>\Library\lib\jvm`. However, the JVM is still installed in `<env_root>\Library`. This causes problems with applications that rely on the `JAVA_HOME` variable which now points to a location that does not exist. See the below example where I tried to use maven but it only succeeded after I changed the `JAVA_HOME` to `<env_root>\Library` manually (not that the build failure is expected and shows that maven is working).

I noticed that the commit linked above did not adapt the [`recipe/bld.bat`](https://github.com/conda-forge/openjdk-feedstock/blob/java11/recipe/bld.bat) file to install the library to the new location.

Demo:
```
(openjdk-env) C:\Users\benjamin>java -version
openjdk version "11.0.15" 2022-04-19 LTS
OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.56+19-CA (build 11.0.15+10-LTS, mixed mode)

(openjdk-env) C:\Users\benjamin>echo %JAVA_HOME%
C:\Users\benjamin\miniconda3\envs\openjdk-env\Library\lib\jvm

(openjdk-env) C:\Users\benjamin>dir %JAVA_HOME%
 Volume in drive C has no label.
 Volume Serial Number is 6AB3-226D

 Directory of C:\Users\benjamin\miniconda3\envs\openjdk-env\Library\lib

File Not Found

(openjdk-env) C:\Users\benjamin>mvn
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE

(openjdk-env) C:\Users\benjamin>set JAVA_HOME=C:\Users\benjamin\miniconda3\envs\openjdk-env\Library

(openjdk-env) C:\Users\benjamin>mvn
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.126 s
[INFO] Finished at: 2022-09-28T13:55:29+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException
```

### Installed packages

```shell
# packages in environment at C:\Users\benjamin\miniconda3\envs\openjdk-env:
#
# Name                    Version                   Build  Channel
maven                     3.8.1                haa95532_0
openjdk                   11.0.15              h57928b3_2    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vs2015_runtime            14.29.30139          h890b9b1_7    conda-forge
```

### Environment info

```shell
active environment : openjdk-env
    active env location : C:\Users\benjamin\miniconda3\envs\openjdk-env
            shell level : 2
       user config file : C:\Users\benjamin\.condarc
 populated config files :
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\benjamin\miniconda3  (writable)
      conda av data dir : C:\Users\benjamin\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\benjamin\miniconda3\pkgs
                          C:\Users\benjamin\.conda\pkgs
                          C:\Users\benjamin\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\benjamin\miniconda3\envs
                          C:\Users\benjamin\.conda\envs
                          C:\Users\benjamin\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by beenje**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Fix #107 for openjdk 11

- copy all files under `%LIBRARY_PREFIX%\lib\jvm`
- modify `PATH` to include `%LIBRARY_PREFIX%\lib\jvm\bin`

### CODE REVIEW

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

File: recipe/scripts/deactivate-win.sh [hunk 1]
```diff
@@ -1,3 +1,4 @@
+export PATH=$(echo $PATH | sed "s?$JAVA_HOME/bin:??")
```
Comment (beenje) [inline recipe/scripts/deactivate-win.sh:1]: I have done this in another recipe on Linux. Not sure this will work with posix cli on windows.

Comment (izahn) [reply recipe/scripts/deactivate-win.sh:1]: Rather than mucking about with the PATH I recommend putting a link in the standard places, e.g., as done in https://github.com/conda-forge/openjdk-feedstock/blob/c205caaa29d765fcf79dd4ea6bcd9f162879ee53/recipe/build.sh#L221

Comment (beenje) [reply recipe/scripts/deactivate-win.sh:1]: I don't know much about windows. The `bin` directory contains both `.exe` and `.dll`.
Can I create link only for `.exe` files?
My understanding from https://github.com/conda-forge/openjdk-feedstock/issues/86 is that we don't want the `.dll` (like `zip.dll`) in the default bin directory to avoid conflicts.

I tried using the following command but it didn't work:

```
for %%f in (%INSTALL_DIR%\bin\*.exe) do (
    mklink "%LIBRARY_BIN%\%%~nf.exe" %%f
)
```

Looks like you have to be admin on windows to create links. There is `mklink /J` but that is for directory only.

Do you have another solution than changing the PATH?

Comment (izahn) [reply recipe/scripts/deactivate-win.sh:1]: I think we want to link .exe files only, and link them to `%PREFIX%\bin\`

Comment (beenje) [reply recipe/scripts/deactivate-win.sh:1]: How do you create link on windows as normal user?

Comment (izahn) [reply recipe/scripts/deactivate-win.sh:1]: Oh hmmm, one more reason to hate windows :-(

Comment (beenje) [reply recipe/scripts/deactivate-win.sh:1]: Again, not a windows expert but I've never seen a recipe creating links under windows.
So I think the current implementation (modifying the PATH) is probably the way to go. I tested the `activate.bat` and `deactivate.bat`. They work as expected. I'm just not 100% sure about the `activate-win.sh` / `deactivate-win.sh` as I don't know when they are used exactly. But on Linux, this shell script would work fine.

Comment (beenje) [reply recipe/scripts/deactivate-win.sh:1]: I have a Windows VM and tested it locally.

**Comment by izahn** [comment]
@conda-forge/openjdk anyone have a position on this? Our current packages are broken on Windows (https://github.com/conda-forge/openjdk-feedstock/issues/107 ), so we need a fix along these lines. I just don't know windows well enough to feel confident merging this without a second opinion.

**Comment by xhochy** [comment]
I would rather revert the change of the `JAVA_HOME` variable on Windows than move the whole JDK to a different place. Fiddling with PATH in Windows sounds unnecessary to me.

**Comment by mbargull** [comment]
We should not make changes to `PATH` in activate script whenever possible; it's just to brittle (many many edge cases).
I can help with getting an alternative to symlinks on Windows (little launcher `.exe`s that we can take over the symlinks' job).
I might only get to that in a few days (beginning next week at the latest).

Can we please mark the current Windows builds `broken` in the meantime? I.e., can one of you submit a PR to https://github.com/conda-forge/admin-requests for the affected builds?

**Comment by xhochy** [comment]
> I can help with getting an alternative to symlinks on Windows (little launcher .exes that we can take over the symlinks' job).
I might only get to that in a few days (beginning next week at the latest).

If we go with the put-JDK-not-into-separate-directory-structure-approach (most likely) than this would also be my preferred approach 👍 @mbargull Your help here is very appreciated!

**Comment by mbargull** [comment]
Working on it as we speak. (Things are always slower for me when dealing with Windows...)
I should be able to submit a new package to staged-recipes later today or to tomorrow that we can then use here and in other places.

**Comment by mbargull** [comment]
Please review https://github.com/conda-forge/staged-recipes/pull/20883 .
With that we can turn a
```sh
ln -s -r -f "$INSTALL_DIR/bin/$i" "$PREFIX/bin/$i" 
```
to something like
```cmd
call build-symlink-exe "%INSTALL_DIR%\bin\%%i" "%PREFIX%\Scripts"
```
... and then we should add tests like `%JAVA_HOME%\bin\javac --version` to this recipe to avoid regressions.

**Comment by mbargull** [comment]
The build logs now show
```
WARNING (openjdk,Library/bin/javap.exe): .. but ['ucrt'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
```
and similar. This is correct, but a meta-package `symlink-exe-runtime`, which depends on `ucrt`, is added to the run requirements via `run_exports`. I.e., working correct and as intended. (Okay, if the warnings bother someone they can add `- {{ compiler('c') }} # [win]` to requirements/build).

**Comment by beenje** [comment]
Thanks @mbargull!

**Comment by h-vetinari** [comment]
Yes, thanks a lot! :)

**Comment by izahn** [comment]
I would feel better if we had a test that fails in the main branch but passes here. Anybody have an easy way to trigger an error?

**Comment by h-vetinari** [comment]
> I would feel better if we had a test that fails in the main branch but passes here. Anybody have an easy way to trigger an error?

Aside from the fact that it'd probably need to be the `java11` branch (as not many projects are on jdk 17 yet), you could add a `downstreams:` section to the tests, and run the test suite of one of the affected feedstocks.

This is assuming that the error also appears at test (not just build) time, but given that it's about the detection of `JAVA_HOME`, I think this will probably also surface the error.

**Comment by mbargull** [comment]
> I would feel better if we had a test that fails in the main branch but passes here. Anybody have an easy way to trigger an error?

I added `%JAVA_HOME%\bin\java -version` here. That one should already fail on `main`.

**Comment by mbargull** [comment]
@conda-forge-admin, please rerender

**Comment by mbargull** [comment]
@conda-forge/openjdk, good to merge?

**Review by izahn — APPROVED** [review]

**Review by xhochy — APPROVED** [review]
